name: organ-skin-tracer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pyvista>=0.40.0
  - vtk>=9.0.0
  - matplotlib>=3.5.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - pip
  - pip:
    - pathlib2>=2.3.0
    - trimesh>=3.9.0
    - open3d>=0.13.0 